### ISSUE TITLE
Revisar Práctico 1

### ISSUE THREAD

**Issue by jaarac** [estebancere/practicos-vision-artificial#1]
No me funcionó:

PROGRAMA ADIVINADOR
PROGRAMA ADIVINADOR
Ingrese el numero de intentos 5
El numero random es 37
Ingrese un numero entre 0 y 100 4
El numero ingresado es 4
NO ADIVINASTE!
Te quedan 4 intentos
ACERTASTE!! fue en el intento 1
GAME OVER

**Comment by estebancere** [comment]
Ya lo reviso. Gracias. Saludos!

**Comment by estebancere** [comment]
Ahi lo corregí Profe, cualquier cosa me avisa. ¡Saludos!
